site_name: PHIS2
theme: bootstrap
extra_css:
   - "css/bootstrap.css"
   - "css/site.css"
   - "css/navbar.less"
pages:
   - Home: index.md
   - Experimental Organization: experimental-organization.md
   - Community: community.md
   - Clients: ws-clients.md
